// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: daemon/daemon.proto

package daemon

import (
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PreRunReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CmdKey string `protobuf:"bytes,1,opt,name=cmd_key,json=cmdKey,proto3" json:"cmd_key,omitempty"`
}

func (x *PreRunReportResponse) Reset() {
	*x = PreRunReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_daemon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreRunReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreRunReportResponse) ProtoMessage() {}

func (x *PreRunReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreRunReportResponse.ProtoReflect.Descriptor instead.
func (*PreRunReportResponse) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *PreRunReportResponse) GetCmdKey() string {
	if x != nil {
		return x.CmdKey
	}
	return ""
}

type PreRunQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command   string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Tty       string `protobuf:"bytes,2,opt,name=tty,proto3" json:"tty,omitempty"`
	Timestamp int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *PreRunQueryRequest) Reset() {
	*x = PreRunQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_daemon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreRunQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreRunQueryRequest) ProtoMessage() {}

func (x *PreRunQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreRunQueryRequest.ProtoReflect.Descriptor instead.
func (*PreRunQueryRequest) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *PreRunQueryRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *PreRunQueryRequest) GetTty() string {
	if x != nil {
		return x.Tty
	}
	return ""
}

func (x *PreRunQueryRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PreRunQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *PreRunQueryResponse) Reset() {
	*x = PreRunQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_daemon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreRunQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreRunQueryResponse) ProtoMessage() {}

func (x *PreRunQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreRunQueryResponse.ProtoReflect.Descriptor instead.
func (*PreRunQueryResponse) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *PreRunQueryResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type PostRunReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ExitCode int32  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
}

func (x *PostRunReportRequest) Reset() {
	*x = PostRunReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_daemon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostRunReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRunReportRequest) ProtoMessage() {}

func (x *PostRunReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRunReportRequest.ProtoReflect.Descriptor instead.
func (*PostRunReportRequest) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *PostRunReportRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PostRunReportRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type CommandEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command   string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Tty       string `protobuf:"bytes,2,opt,name=tty,proto3" json:"tty,omitempty"`
	Timestamp int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *CommandEntry) Reset() {
	*x = CommandEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_daemon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEntry) ProtoMessage() {}

func (x *CommandEntry) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEntry.ProtoReflect.Descriptor instead.
func (*CommandEntry) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *CommandEntry) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandEntry) GetTty() string {
	if x != nil {
		return x.Tty
	}
	return ""
}

func (x *CommandEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CommandKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *CommandKey) Reset() {
	*x = CommandKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_daemon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandKey) ProtoMessage() {}

func (x *CommandKey) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandKey.ProtoReflect.Descriptor instead.
func (*CommandKey) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *CommandKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CommandExitCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ExitCode int32  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
}

func (x *CommandExitCode) Reset() {
	*x = CommandExitCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daemon_daemon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandExitCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandExitCode) ProtoMessage() {}

func (x *CommandExitCode) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandExitCode.ProtoReflect.Descriptor instead.
func (*CommandExitCode) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *CommandExitCode) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CommandExitCode) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_daemon_daemon_proto protoreflect.FileDescriptor

var file_daemon_daemon_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x64, 0x2e, 0x64, 0x61,
	0x65, 0x6d, 0x6f, 0x6e, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x2f, 0x0a, 0x14, 0x50, 0x72, 0x65, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6d, 0x64,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6d, 0x64, 0x4b,
	0x65, 0x79, 0x22, 0x5e, 0x0a, 0x12, 0x50, 0x72, 0x65, 0x52, 0x75, 0x6e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x74, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0x29, 0x0a, 0x13, 0x50, 0x72, 0x65, 0x52, 0x75, 0x6e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x47, 0x0a,
	0x14, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x69,
	0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x78,
	0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x58, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74,
	0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x22, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x40, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x45, 0x78, 0x69, 0x74, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x32, 0xb7, 0x01, 0x0a, 0x11, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x54, 0x0a, 0x0b, 0x50, 0x72, 0x65, 0x52,
	0x75, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x21, 0x2e, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x64,
	0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x65, 0x52, 0x75, 0x6e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x68, 0x65,
	0x6c, 0x6c, 0x64, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x65, 0x52, 0x75,
	0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c,
	0x0a, 0x0d, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x23, 0x2e, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x64, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xb0, 0x01, 0x0a,
	0x0f, 0x4d, 0x65, 0x74, 0x61, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e,
	0x12, 0x4d, 0x0a, 0x11, 0x4e, 0x65, 0x77, 0x45, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1e, 0x2e,
	0x73, 0x68, 0x65, 0x6c, 0x6c, 0x64, 0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x45, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x30, 0x01, 0x12,
	0x4e, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1b, 0x2e, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x64,
	0x2e, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x1a, 0x19, 0x2e, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x64, 0x2e, 0x64, 0x61,
	0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x42,
	0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x61,
	0x70, 0x68, 0x61, 0x65, 0x6c, 0x72, 0x65, 0x79, 0x6e, 0x61, 0x2f, 0x73, 0x68, 0x65, 0x6c, 0x6c,
	0x64, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_daemon_daemon_proto_rawDescOnce sync.Once
	file_daemon_daemon_proto_rawDescData = file_daemon_daemon_proto_rawDesc
)

func file_daemon_daemon_proto_rawDescGZIP() []byte {
	file_daemon_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_daemon_daemon_proto_rawDescData)
	})
	return file_daemon_daemon_proto_rawDescData
}

var file_daemon_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_daemon_daemon_proto_goTypes = []interface{}{
	(*PreRunReportResponse)(nil), // 0: shelld.daemon.PreRunReportResponse
	(*PreRunQueryRequest)(nil),   // 1: shelld.daemon.PreRunQueryRequest
	(*PreRunQueryResponse)(nil),  // 2: shelld.daemon.PreRunQueryResponse
	(*PostRunReportRequest)(nil), // 3: shelld.daemon.PostRunReportRequest
	(*CommandEntry)(nil),         // 4: shelld.daemon.CommandEntry
	(*CommandKey)(nil),           // 5: shelld.daemon.CommandKey
	(*CommandExitCode)(nil),      // 6: shelld.daemon.CommandExitCode
	(*empty.Empty)(nil),          // 7: google.protobuf.Empty
}
var file_daemon_daemon_proto_depIdxs = []int32{
	1, // 0: shelld.daemon.ShellclientDaemon.PreRunQuery:input_type -> shelld.daemon.PreRunQueryRequest
	3, // 1: shelld.daemon.ShellclientDaemon.PostRunReport:input_type -> shelld.daemon.PostRunReportRequest
	7, // 2: shelld.daemon.MetashellDaemon.NewExitCodeStream:input_type -> google.protobuf.Empty
	4, // 3: shelld.daemon.MetashellDaemon.RegisterCommandEntry:input_type -> shelld.daemon.CommandEntry
	2, // 4: shelld.daemon.ShellclientDaemon.PreRunQuery:output_type -> shelld.daemon.PreRunQueryResponse
	7, // 5: shelld.daemon.ShellclientDaemon.PostRunReport:output_type -> google.protobuf.Empty
	6, // 6: shelld.daemon.MetashellDaemon.NewExitCodeStream:output_type -> shelld.daemon.CommandExitCode
	5, // 7: shelld.daemon.MetashellDaemon.RegisterCommandEntry:output_type -> shelld.daemon.CommandKey
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_daemon_daemon_proto_init() }
func file_daemon_daemon_proto_init() {
	if File_daemon_daemon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_daemon_daemon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreRunReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_daemon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreRunQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_daemon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreRunQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_daemon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostRunReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_daemon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_daemon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daemon_daemon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandExitCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_daemon_daemon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_daemon_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_daemon_proto_depIdxs,
		MessageInfos:      file_daemon_daemon_proto_msgTypes,
	}.Build()
	File_daemon_daemon_proto = out.File
	file_daemon_daemon_proto_rawDesc = nil
	file_daemon_daemon_proto_goTypes = nil
	file_daemon_daemon_proto_depIdxs = nil
}
